[project]
name = "16"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langsmith>=0.4.10",
    "openai-agents>=0.2.4",
    "python-dotenv>=1.1.1",
]
